version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2022.04
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run: make lint
      

workflows:
  deployment:
    jobs:
      - test
