version: 2.1
orbs: 
  aws-eks: circleci/aws-eks@2.1.2
  kubernetes: circleci/kubernetes@1.3.0
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
      - run: make lint
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: make setup
      - persist_to_workspace:
          root: ~/
          paths:
            - project/app
  publish:
    docker:
      - image: cimg/base:stable
        user: root
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          TAG=$CIRCLE_BUILD_NUM
          docker build --tag samadarshad/devops-capstone-app:$TAG .
          docker login -u samadarshad -p $DOCKERHUB_PASSWORD
          docker push samadarshad/devops-capstone-app:$TAG
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: udacity-devops-capstone
          install-kubectl: true
      - kubernetes/update-container-image:
          get-rollout-status: true
          resource-file-path: deployment/udacity-devops-capstone
          container-image-updates: 'samadarshad/devops-capstone-app=samadarshad/devops-capstone-app:$CIRCLE_BUILD_NUM'
      - run: kubectl get pods


workflows:
  deployment:
    jobs:
      - test
      - build:
          requires: [test]
      - publish:
          requires: [build]
      - deploy:
          requires: [build]
